In [78]:
import numpy as np
def simulate_data(seed: int = 481) -> tuple:
    np.random.seed(seed)
    obs = 1000
    # generates x values
    x1 = np.random.normal(0, np.sqrt(2), size = obs)
    x2 = np.random.normal(0, np.sqrt(2), size = obs)
    x3 = np.random.normal(0, np.sqrt(2), size = obs)
    # generates error values
    e = np.random.normal(0, 1, size = obs)
    # generates y values
    y = 5 + 3*x1 + 2 * x2 + 6 * x3 + e
    # generates X 3D array
    X = np.array([x1, x2, x3]).T
    return y,X

y, X = simulate_data(5)

import numpy as np
import scipy as sp
def estimate_mle(y: np.array, X: np.array) -> np.array:
    def negll(beta: np.array, y, X):
        beta0, beta1, beta2, beta3 = beta
        n = len(y)
        sigsq = 1
        yhat = beta0 + beta1 * X[:, 0] + beta2 * X[:, 1] + beta3 * X[:, 2]
        log_l = -(n/2) * np.log(2 * np.pi * sigsq) - (1/(2 * sigsq)) * np.sum((y - yhat)**2)
        return -log_l
    initial_b = np.zeros(4)
    result_b = sp.optimize.minimize(negll, initial_b, args=(y,X), method = 'Nelder-Mead')
    return result_b.x
print(estimate_mle(y,X))

[5.06224431 2.99466161 1.99520722 6.02141795]


In [40]:
np.mean(X)
np.mean(y)

4.786848384396221

In [79]:
import numpy as np
import scipy as sp
def estimate_mle(y: np.array, X: np.array) -> np.array:
    def negll(beta: np.array, y, X):
        beta0, beta1, beta2, beta3 = beta
        n = len(y)
        sigsq = 1
        yhat = beta0 + beta1 * X[:, 0] + beta2 * X[:, 1] + beta3 * X[:, 2]
        log_l = -(n/2) * np.log(2 * np.pi * sigsq) - (1/(2 * sigsq)) * np.sum((y - yhat)**2)
        return -log_l
    initial_b = [0, 0, 0, 0]
    result_b = sp.optimize.minimize(negll, initial_b, args=(y,X), method = 'Nelder-Mead')
    return result_b.x
print(estimate_mle(y,X))

[5.06224431 2.99466161 1.99520722 6.02141795]


In [81]:
def estimate_ols(y: np.array, X: np.array) -> np.array:
    def sse(beta: np.array, X: np.array, y: np.array):
        return np.sum((y - (X @ beta)) ** 2)
    X = np.hstack((np.ones((X.shape[0], 1)), X))
    b_initial = np.zeros(4)
    b_result = sp.optimize.minimize(sse, b_initial, args = (X, y), method = 'Nelder-Mead')
    return b_result.x
print(estimate_ols(y,X))

[5.06224431 2.99466161 1.99520722 6.02141795]


In [ ]:
def github() -> str:
    return "https://github.com/kalvinlee/ECON481/blob/main/problemset2.py"