In [143]:
import numpy as np
def simulate_data(seed: int = 481) -> tuple:
    np.random.seed(seed)
    # generates x values
    x_1 = np.random.normal(0, np.sqrt(2), 1000)
    x_2 = np.random.normal(0, np.sqrt(2), 1000)
    x_3 = np.random.normal(0, np.sqrt(2), 1000)
    # generates error values
    e = np.random.normal(0, 1, 1000)
    # generates X array
    X = np.column_stack((x_1, x_2, x_3))
    # generates y values
    y = 5 + 3*x_1 + 2*x_2 + 6*x_3 + e
    return y,X

y,X = simulate_data(480)
print(y.shape)
print(X.shape)

import numpy as np
import scipy as sp
def estimate_mle(y: np.array, X: np.array) -> np.array:
    def negll(beta: np.array, y: np.array, X: np.array):
        beta0, beta1, beta2, beta3 = beta
        n = len(y)
        sigsq = 1
        yhat = beta0 + beta1 * X[:, 0] + beta2 * X[:, 1] + beta3 * X[:, 2]
        log_l = -(n/2) * np.log(2 * np.pi * sigsq) - (1/(2 * sigsq)) * np.sum((y - yhat)**2)
        return -log_l
    initial_b = np.zeros(4)
    result_b = sp.optimize.minimize(negll, initial_b, args=(y,X), method = 'Nelder-Mead')
    return result_b.x
print(estimate_mle(y,X))

print(y)

(1000,)
(1000, 3)
[5.00254143 2.98163093 2.00818951 6.01690999]
[ 4.92977515e+00  1.94878332e+01  2.35163425e+00 -1.15276747e-01
  1.54701716e+01  2.34760564e+01  1.51289171e+01 -5.87876291e+00
  1.08995117e+01  1.80008275e+00  6.02589837e+00  8.35541914e+00
  1.32310128e+01 -5.89713846e+00 -1.38074921e+01  9.22154860e+00
 -6.13398200e+00 -5.87000483e+00  1.66084114e+01  2.24402662e+01
 -4.43924789e+00  4.00175782e+00 -4.29484120e+00 -8.83758332e+00
 -7.58775239e+00  3.00026936e+00  1.76227818e+00 -8.06438533e+00
  3.72314049e+00  6.14445232e+00 -4.19496694e+00  1.20690877e+01
 -3.13913919e+00  1.36666598e+00  1.31109065e+01  1.05071055e+01
 -3.73611275e+00  1.22115459e+01 -7.18074214e+00  1.47711601e+00
 -6.16052105e-01  5.45491943e+00 -2.45490156e+00  1.22326033e+01
  9.01184007e+00  1.37075687e+01  6.34030686e+00  1.45921168e+00
  1.79154599e+01 -2.21137997e+00  1.47217296e+01  4.53642372e+00
  5.26580794e+00  1.58317388e+01 -1.78834370e+00  2.54537401e+01
  3.95107514e+00  2.195542

In [136]:
import numpy as np
import scipy as sp
def estimate_mle(y: np.array, X: np.array) -> np.array:
    def negll(beta: np.array, y, X):
        beta0, beta1, beta2, beta3 = beta
        n = len(y)
        sigsq = 1
        yhat = beta0 + beta1 * X[:, 0] + beta2 * X[:, 1] + beta3 * X[:, 2]
        log_l = -(n/2) * np.log(2 * np.pi * sigsq) - (1/(2 * sigsq)) * np.sum((y - yhat)**2)
        return -log_l
    initial_b = [0, 0, 0, 0]
    result_b = sp.optimize.minimize(negll, initial_b, args=(y,X), method = 'Nelder-Mead')
    return result_b.x
print(estimate_mle(y,X))

[4.98416465 2.97563046 2.00646975 5.99215604]


In [137]:
import numpy as np
import scipy as sp
def estimate_ols(y: np.array, X: np.array) -> np.array:
    def sse(beta: np.array, X: np.array, y: np.array):
        return np.sum((y - (X @ beta)) ** 2)
    X = np.concatenate((np.ones((X.shape[0], 1)), X), axis = 1)
    b_initial = np.zeros(4)
    b_result = sp.optimize.minimize(sse, b_initial, args = (X, y), method = 'Nelder-Mead')
    return b_result.x
print(estimate_ols(y,X))

[4.98416465 2.97563046 2.00646975 5.99215604]


In [83]:
def github() -> str:
    return "https://github.com/kalvinlee/ECON481/blob/main/problemset2.py"
github()

'https://github.com/kalvinlee/ECON481/blob/main/problemset2.py'